// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Booking documents */
interface BookingDocumentData {
  /**
   * Title field in *Booking*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Description field in *Booking*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Image field in *Booking*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small" | "Big">;
  /**
   * IframeUrl field in *Booking*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.iframeurl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  iframeurl: prismic.LinkField;
  /**
   * Distance field in *Booking*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Distance in km
   * - **API ID Path**: booking.distance
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  distance: prismic.NumberField;
  /**
   * Gallery field in *Booking*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  gallery: prismic.GroupField<Simplify<BookingDocumentDataGalleryItem>>;
  /**
   * Info field in *Booking*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.info[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  info: prismic.GroupField<Simplify<BookingDocumentDataInfoItem>>;
  /**
   * Slice Zone field in *Booking*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<BookingDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Booking*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: booking.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Title field in *Booking*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: booking.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Item in Booking → Gallery
 *
 */
export interface BookingDocumentDataGalleryItem {
  /**
   * Image field in *Booking → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.gallery[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small" | "Big">;
}
/**
 * Item in Booking → Info
 *
 */
export interface BookingDocumentDataInfoItem {
  /**
   * Icon field in *Booking → Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.info[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<"Small">;
  /**
   * Info text field in *Booking → Info*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.info[].info_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  info_text: prismic.TitleField;
  /**
   * Info value field in *Booking → Info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.info[].info_value
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  info_value: prismic.RichTextField;
}
/**
 * Slice for *Booking → Slice Zone*
 *
 */
type BookingDocumentDataSlicesSlice = never;
/**
 * Booking document from Prismic
 *
 * - **API ID**: `booking`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BookingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BookingDocumentData>,
    "booking",
    Lang
  >;
/** Content for Navigation documents */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
  /**
   * Button Link field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Button Text field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_text: prismic.RichTextField;
}
/**
 * Item in Navigation → Links
 *
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  label: prismic.TitleField;
  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice =
  | FeaturesSlice
  | ProcedureSlice
  | RealizaceSlice
  | TextWithImageSlice
  | HeroSlice
  | ImageSlice
  | TextWithFeaturesSlice
  | ReviewsSlice
  | TextWithImagesSlice
  | ImageFullScreenSlice
  | BookingsSlice
  | GallerySlice
  | TripsNewSlice
  | ContactSlice
  | CollectionSlice
  | ImageZoomSlice
  | TextColoredBgSlice
  | SliderSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Reference documents */
interface ReferenceDocumentData {
  /**
   * Firma field in *Reference*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Image field in *Reference*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small" | "Big">;
  /**
   * Date field in *Reference*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  date: prismic.DateField;
  /**
   * Short Description field in *Reference*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  short_description: prismic.RichTextField;
  /**
   * Slice Zone field in *Reference*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ReferenceDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Reference*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: reference.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Title field in *Reference*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: reference.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Reference → Slice Zone*
 *
 */
type ReferenceDocumentDataSlicesSlice = never;
/**
 * Reference document from Prismic
 *
 * - **API ID**: `reference`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReferenceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReferenceDocumentData>,
    "reference",
    Lang
  >;
/** Content for Review documents */
interface ReviewDocumentData {
  /**
   * Name field in *Review*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: review.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismic.TitleField;
  /**
   * Image field in *Review*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: review.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Text field in *Review*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Review text
   * - **API ID Path**: review.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Date field in *Review*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: review.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  date: prismic.DateField;
  /**
   * Stars field in *Review*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 5
   * - **API ID Path**: review.stars
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  stars: prismic.SelectField<"5" | "4" | "3" | "2" | "1" | "0", "filled">;
  /**
   * Slice Zone field in *Review*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: review.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ReviewDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: review.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Review*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: review.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: review.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Review → Slice Zone*
 *
 */
type ReviewDocumentDataSlicesSlice = never;
/**
 * Review document from Prismic
 *
 * - **API ID**: `review`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ReviewDocumentData>, "review", Lang>;
/** Content for Settings documents */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  siteTitle: prismic.TitleField;
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismic.ImageField<"Icon" | "Navigation">;
  /**
   * copyright field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  copyright: prismic.RichTextField;
  /**
   * Cookies field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cookies
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  cookies: prismic.RichTextField;
  /**
   * Cookies Button field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cookies_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  cookies_button: prismic.KeyTextField;
  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  email: prismic.KeyTextField;
  /**
   * Telephone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  telephone: prismic.KeyTextField;
  /**
   * Socials field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>;
}
/**
 * Item in Settings → Socials
 *
 */
export interface SettingsDocumentDataSocialsItem {
  /**
   * Logo field in *Settings → Socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismic.ImageField<never>;
  /**
   * Link field in *Settings → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;
/** Content for Trip documents */
interface TripDocumentData {
  /**
   * Title field in *Trip*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Description field in *Trip*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Image field in *Trip*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small" | "Big">;
  /**
   * Rating field in *Trip*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: trip.rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  rating: prismic.SelectField<"1" | "2" | "3" | "4" | "5", "filled">;
  /**
   * Distance field in *Trip*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Distance in km
   * - **API ID Path**: trip.distance
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  distance: prismic.NumberField;
  /**
   * Gallery field in *Trip*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  gallery: prismic.GroupField<Simplify<TripDocumentDataGalleryItem>>;
  /**
   * Info field in *Trip*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.info[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  info: prismic.GroupField<Simplify<TripDocumentDataInfoItem>>;
  /**
   * Season field in *Trip*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Summer
   * - **API ID Path**: trip.season
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  season: prismic.SelectField<"Summer" | "Winter", "filled">;
  /**
   * Slice Zone field in *Trip*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<TripDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Trip*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: trip.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Title field in *Trip*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: trip.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Item in Trip → Gallery
 *
 */
export interface TripDocumentDataGalleryItem {
  /**
   * Image field in *Trip → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.gallery[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small" | "Big">;
}
/**
 * Item in Trip → Info
 *
 */
export interface TripDocumentDataInfoItem {
  /**
   * Icon field in *Trip → Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.info[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<"Small">;
  /**
   * Info text field in *Trip → Info*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.info[].info_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  info_text: prismic.TitleField;
  /**
   * Info value field in *Trip → Info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip.info[].info_value
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  info_value: prismic.RichTextField;
}
/**
 * Slice for *Trip → Slice Zone*
 *
 */
type TripDocumentDataSlicesSlice = never;
/**
 * Trip document from Prismic
 *
 * - **API ID**: `trip`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TripDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TripDocumentData>, "trip", Lang>;
export type AllDocumentTypes =
  | BookingDocument
  | NavigationDocument
  | PageDocument
  | ReferenceDocument
  | ReviewDocument
  | SettingsDocument
  | TripDocument;
/**
 * Primary content in Bookings → Primary
 *
 */
interface BookingsSliceDefaultPrimary {
  /**
   * Text field in *Bookings → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bookings.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button text field in *Bookings → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bookings.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_text: prismic.RichTextField;
  /**
   * Button Link field in *Bookings → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: bookings.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Visible field in *Bookings → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: bookings.primary.visible
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  visible: prismic.NumberField;
}
/**
 * Default variation for Bookings Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BookingsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookingsSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Bookings*
 *
 */
type BookingsSliceVariation = BookingsSliceDefault;
/**
 * Bookings Shared Slice
 *
 * - **API ID**: `bookings`
 * - **Description**: `Bookings`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BookingsSlice = prismic.SharedSlice<
  "bookings",
  BookingsSliceVariation
>;
/**
 * Primary content in Collection → Primary
 *
 */
interface CollectionSliceDefaultPrimary {
  /**
   * Text field in *Collection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text in center
   * - **API ID Path**: collection.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button Text field in *Collection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField;
  /**
   * Button Link field in *Collection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Image 1 field in *Collection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.primary.image_1
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_1: prismic.ImageField<"Small">;
  /**
   * Image 2 field in *Collection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.primary.image_2
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_2: prismic.ImageField<"Small">;
  /**
   * Image 3 field in *Collection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.primary.image_3
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_3: prismic.ImageField<"Small">;
  /**
   * Image 4 field in *Collection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.primary.image_4
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_4: prismic.ImageField<"Small">;
}
/**
 * Default variation for Collection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollectionSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Collection*
 *
 */
type CollectionSliceVariation = CollectionSliceDefault;
/**
 * Collection Shared Slice
 *
 * - **API ID**: `collection`
 * - **Description**: `Collection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSlice = prismic.SharedSlice<
  "collection",
  CollectionSliceVariation
>;
/**
 * Primary content in Contact → Primary
 *
 */
interface ContactSliceDefaultPrimary {
  /**
   * Text field in *Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above contact form
   * - **API ID Path**: contact.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Contact*
 *
 */
type ContactSliceVariation = ContactSliceDefault;
/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: `Contact`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;
/**
 * Primary content in Features → Primary
 *
 */
interface FeaturesSliceDefaultPrimary {
  /**
   * Text field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Link field in *Features → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Button text field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField;
}
/**
 * Item in Features → Items
 *
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Icon field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<never>;
  /**
   * Text field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;
/**
 * Slice variation for *Features*
 *
 */
type FeaturesSliceVariation = FeaturesSliceDefault;
/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;
/**
 * Primary content in Gallery → Primary
 *
 */
interface GallerySliceDefaultPrimary {
  /**
   * Text field in *Gallery → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above gallery
   * - **API ID Path**: gallery.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Item in Gallery → Items
 *
 */
export interface GallerySliceDefaultItem {
  /**
   * Image field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small">;
}
/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;
/**
 * Slice variation for *Gallery*
 *
 */
type GallerySliceVariation = GallerySliceDefault;
/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: `Gallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introductory text for the page
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceWithButtonPrimary {
  /**
   * Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introductory text for the page
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttonText: prismic.KeyTextField;
  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  buttonLink: prismic.LinkField;
  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * With Button variation for Hero Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceWithButton = prismic.SharedSliceVariation<
  "withButton",
  Simplify<HeroSliceWithButtonPrimary>,
  never
>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithButton;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceWhitePrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * With Accent field in *Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  withAccent: prismic.BooleanField;
}
/**
 * White variation for Image Slice
 *
 * - **API ID**: `white`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceWhite = prismic.SharedSliceVariation<
  "white",
  Simplify<ImageSliceWhitePrimary>,
  never
>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceLightSlatePrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * With Accent field in *Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  withAccent: prismic.BooleanField;
}
/**
 * Light Slate variation for Image Slice
 *
 * - **API ID**: `lightSlate`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceLightSlate = prismic.SharedSliceVariation<
  "lightSlate",
  Simplify<ImageSliceLightSlatePrimary>,
  never
>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceWhite | ImageSliceLightSlate;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;
/**
 * Primary content in ImageFullScreen → Primary
 *
 */
interface ImageFullScreenSliceDefaultPrimary {
  /**
   * Image field in *ImageFullScreen → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_full_screen.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Text field in *ImageFullScreen → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_full_screen.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button Text field in *ImageFullScreen → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_full_screen.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField;
  /**
   * Link field in *ImageFullScreen → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_full_screen.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for ImageFullScreen Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageFullScreenSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageFullScreenSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ImageFullScreen*
 *
 */
type ImageFullScreenSliceVariation = ImageFullScreenSliceDefault;
/**
 * ImageFullScreen Shared Slice
 *
 * - **API ID**: `image_full_screen`
 * - **Description**: `ImageFullScreen`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageFullScreenSlice = prismic.SharedSlice<
  "image_full_screen",
  ImageFullScreenSliceVariation
>;
/**
 * Primary content in ImageZoom → Primary
 *
 */
interface ImageZoomSliceDefaultPrimary {
  /**
   * Text field in *ImageZoom → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_zoom.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Image field in *ImageZoom → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_zoom.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Desktop" | "Mobile">;
  /**
   * Bottom Text field in *ImageZoom → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_zoom.primary.bottom_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  bottom_text: prismic.RichTextField;
}
/**
 * Default variation for ImageZoom Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageZoomSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageZoomSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ImageZoom*
 *
 */
type ImageZoomSliceVariation = ImageZoomSliceDefault;
/**
 * ImageZoom Shared Slice
 *
 * - **API ID**: `image_zoom`
 * - **Description**: `ImageZoom`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageZoomSlice = prismic.SharedSlice<
  "image_zoom",
  ImageZoomSliceVariation
>;
/**
 * Primary content in Procedure → Primary
 *
 */
interface ProcedureSliceDefaultPrimary {
  /**
   * Text field in *Procedure → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button Link field in *Procedure → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Button Text field in *Procedure → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_text: prismic.RichTextField;
}
/**
 * Item in Procedure → Items
 *
 */
export interface ProcedureSliceDefaultItem {
  /**
   * Text field in *Procedure → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for Procedure Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProcedureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcedureSliceDefaultPrimary>,
  Simplify<ProcedureSliceDefaultItem>
>;
/**
 * Primary content in Procedure → Primary
 *
 */
interface ProcedureSliceProcedireWithImagePrimary {
  /**
   * Image field in *Procedure → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * Button Link field in *Procedure → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Button Text field in *Procedure → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_text: prismic.RichTextField;
}
/**
 * Item in Procedure → Items
 *
 */
export interface ProcedureSliceProcedireWithImageItem {
  /**
   * Text field in *Procedure → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: procedure.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Procedire - With Image variation for Procedure Slice
 *
 * - **API ID**: `procedireWithImage`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProcedureSliceProcedireWithImage = prismic.SharedSliceVariation<
  "procedireWithImage",
  Simplify<ProcedureSliceProcedireWithImagePrimary>,
  Simplify<ProcedureSliceProcedireWithImageItem>
>;
/**
 * Slice variation for *Procedure*
 *
 */
type ProcedureSliceVariation =
  | ProcedureSliceDefault
  | ProcedureSliceProcedireWithImage;
/**
 * Procedure Shared Slice
 *
 * - **API ID**: `procedure`
 * - **Description**: `Procedure`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProcedureSlice = prismic.SharedSlice<
  "procedure",
  ProcedureSliceVariation
>;
/**
 * Primary content in Trips → Primary
 *
 */
interface RealizaceSliceDefaultPrimary {
  /**
   * Text field in *Trips → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realizace.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button text field in *Trips → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realizace.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_text: prismic.RichTextField;
  /**
   * Button Link field in *Trips → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: realizace.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Visible field in *Trips → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: realizace.primary.visible
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  visible: prismic.NumberField;
  /**
   * Text summer field in *Trips → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realizace.primary.text_summer
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text_summer: prismic.RichTextField;
  /**
   * Text winter field in *Trips → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realizace.primary.text_winter
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text_winter: prismic.RichTextField;
}
/**
 * Default variation for Trips Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RealizaceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RealizaceSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Trips*
 *
 */
type RealizaceSliceVariation = RealizaceSliceDefault;
/**
 * Trips Shared Slice
 *
 * - **API ID**: `realizace`
 * - **Description**: `Realizace`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RealizaceSlice = prismic.SharedSlice<
  "realizace",
  RealizaceSliceVariation
>;
/**
 * Primary content in Reference → Primary
 *
 */
interface ReferenceSliceDefaultPrimary {
  /**
   * Text field in *Reference → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button text field in *Reference → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_text: prismic.RichTextField;
  /**
   * Button Link field in *Reference → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Visible field in *Reference → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: reference.primary.visible
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  visible: prismic.NumberField;
}
/**
 * Default variation for Reference Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReferenceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReferenceSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Reference*
 *
 */
type ReferenceSliceVariation = ReferenceSliceDefault;
/**
 * Reference Shared Slice
 *
 * - **API ID**: `reference`
 * - **Description**: `Reference`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReferenceSlice = prismic.SharedSlice<
  "reference",
  ReferenceSliceVariation
>;
/**
 * Primary content in Reviews → Primary
 *
 */
interface ReviewsSliceDefaultPrimary {
  /**
   * Text field in *Reviews → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above reviews.
   * - **API ID Path**: reviews.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Reviews*
 *
 */
type ReviewsSliceVariation = ReviewsSliceDefault;
/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: `Reviews`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReviewsSlice = prismic.SharedSlice<
  "reviews",
  ReviewsSliceVariation
>;
/**
 * Primary content in Slider → Primary
 *
 */
interface SliderSliceDefaultPrimary {
  /**
   * Text field in *Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Item in Slider → Items
 *
 */
export interface SliderSliceDefaultItem {
  /**
   * Image field in *Slider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small" | "Normal">;
}
/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  Simplify<SliderSliceDefaultItem>
>;
/**
 * Slice variation for *Slider*
 *
 */
type SliderSliceVariation = SliderSliceDefault;
/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: `Slider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;
/**
 * Primary content in TextColoredBg → Primary
 *
 */
interface TextColoredBgSliceDefaultPrimary {
  /**
   * Text field in *TextColoredBg → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_colored_bg.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Button Link field in *TextColoredBg → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_colored_bg.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField;
  /**
   * Button Text field in *TextColoredBg → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_colored_bg.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField;
}
/**
 * Default variation for TextColoredBg Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextColoredBgSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextColoredBgSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *TextColoredBg*
 *
 */
type TextColoredBgSliceVariation = TextColoredBgSliceDefault;
/**
 * TextColoredBg Shared Slice
 *
 * - **API ID**: `text_colored_bg`
 * - **Description**: `TextColoredBg`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextColoredBgSlice = prismic.SharedSlice<
  "text_colored_bg",
  TextColoredBgSliceVariation
>;
/**
 * Primary content in TextWithFeatures → Primary
 *
 */
interface TextWithFeaturesSliceDefaultPrimary {
  /**
   * Icon field in *TextWithFeatures → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_features.primary.icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<never>;
  /**
   * Text field in *TextWithFeatures → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Primary text with rich formatting
   * - **API ID Path**: text_with_features.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Item in TextWithFeatures → Items
 *
 */
export interface TextWithFeaturesSliceDefaultItem {
  /**
   * Feature Description field in *TextWithFeatures → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of a feature
   * - **API ID Path**: text_with_features.items[].featureDescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  featureDescription: prismic.RichTextField;
}
/**
 * Default variation for TextWithFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextWithFeatures`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithFeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithFeaturesSliceDefaultPrimary>,
  Simplify<TextWithFeaturesSliceDefaultItem>
>;
/**
 * Slice variation for *TextWithFeatures*
 *
 */
type TextWithFeaturesSliceVariation = TextWithFeaturesSliceDefault;
/**
 * TextWithFeatures Shared Slice
 *
 * - **API ID**: `text_with_features`
 * - **Description**: `TextWithFeatures`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithFeaturesSlice = prismic.SharedSlice<
  "text_with_features",
  TextWithFeaturesSliceVariation
>;
/**
 * Primary content in TextWithImage → Primary
 *
 */
interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text displayed next to image
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextWithImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *TextWithImage*
 *
 */
type TextWithImageSliceVariation = TextWithImageSliceDefault;
/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: `TextWithImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;
/**
 * Primary content in TextWithImages → Primary
 *
 */
interface TextWithImagesSliceDefaultPrimary {
  /**
   * Text field in *TextWithImages → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above images
   * - **API ID Path**: text_with_images.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Item in TextWithImages → Items
 *
 */
export interface TextWithImagesSliceDefaultItem {
  /**
   * Text field in *TextWithImages → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_images.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Link field in *TextWithImages → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_images.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
  /**
   * Button text field in *TextWithImages → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_images.items[].button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField;
  /**
   * Image field in *TextWithImages → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_images.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small">;
  /**
   * Image 2 field in *TextWithImages → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_images.items[].image_2
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_2: prismic.ImageField<"Small">;
  /**
   * Image 3 field in *TextWithImages → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_images.items[].image_3
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_3: prismic.ImageField<"Small">;
  /**
   * Image 4 field in *TextWithImages → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_images.items[].image_4
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image_4: prismic.ImageField<"Small">;
}
/**
 * Default variation for TextWithImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImagesSliceDefaultPrimary>,
  Simplify<TextWithImagesSliceDefaultItem>
>;
/**
 * Slice variation for *TextWithImages*
 *
 */
type TextWithImagesSliceVariation = TextWithImagesSliceDefault;
/**
 * TextWithImages Shared Slice
 *
 * - **API ID**: `text_with_images`
 * - **Description**: `TextWithImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithImagesSlice = prismic.SharedSlice<
  "text_with_images",
  TextWithImagesSliceVariation
>;
/**
 * Primary content in TripsNew → Primary
 *
 */
interface TripsNewSliceDefaultPrimary {
  /**
   * Text field in *TripsNew → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above trips
   * - **API ID Path**: trips_new.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Summer field in *TripsNew → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trips_new.primary.summer
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  summer: prismic.ImageField<never>;
  /**
   * Winter field in *TripsNew → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trips_new.primary.winter
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  winter: prismic.ImageField<never>;
}
/**
 * Item in TripsNew → Items
 *
 */
export interface TripsNewSliceDefaultItem {
  /**
   * Image field in *TripsNew → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trips_new.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<"Small">;
  /**
   * Text field in *TripsNew → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Trip description
   * - **API ID Path**: trips_new.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
  /**
   * Season field in *TripsNew → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Summer
   * - **API ID Path**: trips_new.items[].season
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  season: prismic.SelectField<"Summer" | "Winter", "filled">;
}
/**
 * Default variation for TripsNew Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TripsNewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TripsNewSliceDefaultPrimary>,
  Simplify<TripsNewSliceDefaultItem>
>;
/**
 * Slice variation for *TripsNew*
 *
 */
type TripsNewSliceVariation = TripsNewSliceDefault;
/**
 * TripsNew Shared Slice
 *
 * - **API ID**: `trips_new`
 * - **Description**: `TripsNew`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TripsNewSlice = prismic.SharedSlice<
  "trips_new",
  TripsNewSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      BookingDocumentData,
      BookingDocumentDataGalleryItem,
      BookingDocumentDataInfoItem,
      BookingDocumentDataSlicesSlice,
      BookingDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      NavigationDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      ReferenceDocumentData,
      ReferenceDocumentDataSlicesSlice,
      ReferenceDocument,
      ReviewDocumentData,
      ReviewDocumentDataSlicesSlice,
      ReviewDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocialsItem,
      SettingsDocument,
      TripDocumentData,
      TripDocumentDataGalleryItem,
      TripDocumentDataInfoItem,
      TripDocumentDataSlicesSlice,
      TripDocument,
      AllDocumentTypes,
      BookingsSliceDefaultPrimary,
      BookingsSliceDefault,
      BookingsSliceVariation,
      BookingsSlice,
      CollectionSliceDefaultPrimary,
      CollectionSliceDefault,
      CollectionSliceVariation,
      CollectionSlice,
      ContactSliceDefaultPrimary,
      ContactSliceDefault,
      ContactSliceVariation,
      ContactSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceDefault,
      FeaturesSliceVariation,
      FeaturesSlice,
      GallerySliceDefaultPrimary,
      GallerySliceDefaultItem,
      GallerySliceDefault,
      GallerySliceVariation,
      GallerySlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceWithButtonPrimary,
      HeroSliceWithButton,
      HeroSliceVariation,
      HeroSlice,
      ImageSliceWhitePrimary,
      ImageSliceWhite,
      ImageSliceLightSlatePrimary,
      ImageSliceLightSlate,
      ImageSliceVariation,
      ImageSlice,
      ImageFullScreenSliceDefaultPrimary,
      ImageFullScreenSliceDefault,
      ImageFullScreenSliceVariation,
      ImageFullScreenSlice,
      ImageZoomSliceDefaultPrimary,
      ImageZoomSliceDefault,
      ImageZoomSliceVariation,
      ImageZoomSlice,
      ProcedureSliceDefaultPrimary,
      ProcedureSliceDefaultItem,
      ProcedureSliceDefault,
      ProcedureSliceProcedireWithImagePrimary,
      ProcedureSliceProcedireWithImageItem,
      ProcedureSliceProcedireWithImage,
      ProcedureSliceVariation,
      ProcedureSlice,
      RealizaceSliceDefaultPrimary,
      RealizaceSliceDefault,
      RealizaceSliceVariation,
      RealizaceSlice,
      ReferenceSliceDefaultPrimary,
      ReferenceSliceDefault,
      ReferenceSliceVariation,
      ReferenceSlice,
      ReviewsSliceDefaultPrimary,
      ReviewsSliceDefault,
      ReviewsSliceVariation,
      ReviewsSlice,
      SliderSliceDefaultPrimary,
      SliderSliceDefaultItem,
      SliderSliceDefault,
      SliderSliceVariation,
      SliderSlice,
      TextColoredBgSliceDefaultPrimary,
      TextColoredBgSliceDefault,
      TextColoredBgSliceVariation,
      TextColoredBgSlice,
      TextWithFeaturesSliceDefaultPrimary,
      TextWithFeaturesSliceDefaultItem,
      TextWithFeaturesSliceDefault,
      TextWithFeaturesSliceVariation,
      TextWithFeaturesSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceDefault,
      TextWithImageSliceVariation,
      TextWithImageSlice,
      TextWithImagesSliceDefaultPrimary,
      TextWithImagesSliceDefaultItem,
      TextWithImagesSliceDefault,
      TextWithImagesSliceVariation,
      TextWithImagesSlice,
      TripsNewSliceDefaultPrimary,
      TripsNewSliceDefaultItem,
      TripsNewSliceDefault,
      TripsNewSliceVariation,
      TripsNewSlice,
    };
  }
}
