// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  procedure: dynamic(() => import("./Procedure")),
  realizace: dynamic(() => import("./Realizace")),
  reference: dynamic(() => import("./Reference")),
  review: dynamic(() => import("./Review")),
  text_with_features: dynamic(() => import("./TextWithFeatures")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
