// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bookings: dynamic(() => import("./Bookings")),
  collection: dynamic(() => import("./Collection")),
  contact: dynamic(() => import("./Contact")),
  features: dynamic(() => import("./Features")),
  gallery: dynamic(() => import("./Gallery")),
  gallery_new: dynamic(() => import("./GalleryNew")),
  hero: dynamic(() => import("./Hero")),
  icons: dynamic(() => import("./Icons")),
  image: dynamic(() => import("./Image")),
  image_full_screen: dynamic(() => import("./ImageFullScreen")),
  image_zoom: dynamic(() => import("./ImageZoom")),
  partners: dynamic(() => import("./Partners")),
  pricing: dynamic(() => import("./Pricing")),
  procedure: dynamic(() => import("./Procedure")),
  realizace: dynamic(() => import("./Trips")),
  reference: dynamic(() => import("./Reference")),
  reviews: dynamic(() => import("./Reviews")),
  slider: dynamic(() => import("./Slider")),
  text_colored_bg: dynamic(() => import("./TextColoredBg")),
  text_with_features: dynamic(() => import("./TextWithFeatures")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  text_with_images: dynamic(() => import("./TextWithImages")),
  trips_new: dynamic(() => import("./TripsNew")),
};
